@startuml Dependency

skinparam classAttributeIconSize 0

interface StoreInterface {
    + getStoreName(): string
    + getOwnerName(): string
    + getEmployees(): []Employee
}

class CoffeeStore implements StoreInterface {
    - storeName: string
    - owner: Owner
    - employees: []Employee
}

class CakeStore implements StoreInterface {
    - storeName: string
    - owner: Owner
    - employees: []Employee
}

class MainStore {
    + storeInterface: StoreInterface
}

StoreInterface <-- MainStore

@enduml